class QuizQuestion {
  final String question;
  final List<String> options;
  final int correctIndex;
  final String? explanation;
  final String topic;

  const QuizQuestion({
    required this.question,
    required this.options,
    required this.correctIndex,
    this.explanation,
    required this.topic,
  });
}

const List<QuizQuestion> frcpathQuestions = [
  // THYROID PATHOLOGY
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'Which molecular alteration is most commonly associated with invasive encapsulated follicular variant of papillary thyroid carcinoma (EFVPTC)?',
    options: ['BRAF V600E mutation', 'RAS mutation (HRAS/NRAS/KRAS)', 'RET/PTC rearrangement', 'TERT promoter mutation'],
    correctIndex: 1,
    explanation: 'NIFTPs are characterized by a high frequency of RAS mutations, particularly in NRAS, similar to follicular thyroid adenoma.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'A thyroid tumor in a 23-year-old woman shows cribriform areas with spindle-cell morules. Immunostaining shows nuclear β-catenin and ER positivity in morules. Which molecular alteration is MOST commonly associated?',
    options: ['BRAF V600E mutation', 'Germline APC mutation', 'RET/PTC1 fusion', 'HRAS mutation'],
    correctIndex: 1,
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'Congo red stain is positive, but IHC for calcitonin is negative. Which stain would be most helpful to confirm medullary thyroid carcinoma?',
    options: ['Thyroglobulin', 'Chromogranin A', 'TTF-1', 'CK7'],
    correctIndex: 1,
    explanation: 'Chromogranin A confirms neuroendocrine nature of calcitonin-negative MTC.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'A 35-year-old female with a TERT promoter mutation in thyroid tumor. What is the most likely implication?',
    options: ['Indolent course with excellent prognosis', 'Resistance to radioactive iodine', 'Association with familial MTC', 'No impact on prognosis'],
    correctIndex: 1,
    explanation: 'TERT promoter mutations are associated with aggressive behavior and resistance to radioactive iodine.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'KRAS mutation is NOT commonly seen in:',
    options: ['Follicular adenoma', 'NIFTP', 'iFVPTC (invasive follicular variant PTC)', 'enFVPTC'],
    correctIndex: 2,
    explanation: 'Invasive FVPTC does not commonly show KRAS mutations.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'Which has the HIGHEST association with BRAF mutation?',
    options: ['Classic variant PTC', 'Tall cell variant PTC', 'Follicular variant PTC', 'Medullary carcinoma'],
    correctIndex: 1,
    explanation: 'BRAF mutation in tall cell variant PTCs is as high as 80-100%.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'What is the mitotic count criterion for high-grade medullary carcinoma of thyroid?',
    options: ['>5/2 mm²', '>2/2 mm²', '>3/2 mm²', '>10/2 mm²'],
    correctIndex: 0,
    explanation: 'High-grade MTC: mitotic index ≥5 per 2 mm², Ki67 ≥5%, and/or tumor necrosis.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'Which is NOT true about SETTLE tumor of thyroid?',
    options: ['CD5 is used as an IHC marker', 'Occurs in young patients', 'Aggressive behavior', 'Biphasic histology'],
    correctIndex: 2,
    explanation: 'SETTLE is a rare, low-grade malignant thyroid tumor with indolent behavior.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'What are the Turin criteria for mitotic count in poorly differentiated thyroid carcinoma?',
    options: ['Mitosis >3/2 mm²', 'Mitosis >5/2 mm²', 'Mitosis >10/2 mm²', 'Mitosis >2/2 mm²'],
    correctIndex: 0,
    explanation: 'Turin criteria: poorly differentiated thyroid carcinoma shows >3 mitoses per 2 mm².',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'Which mutation is associated with hereditary medullary carcinoma of thyroid?',
    options: ['BRAF', 'KRAS', 'RET', 'P53'],
    correctIndex: 2,
    explanation: 'Germline mutations in the RET gene cause hereditary MTC in MEN2A and MEN2B.',
  ),
  QuizQuestion(
    topic: 'Thyroid Pathology',
    question: 'Cowden syndrome increases risk of malignancy in all EXCEPT:',
    options: ['Thyroid', 'Breast', 'Liver', 'Endometrium'],
    correctIndex: 2,
    explanation: 'HCC risk is lesser in Cowden syndrome compared to thyroid, breast, and endometrium.',
  ),
  // BREAST PATHOLOGY
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'A breast carcinoma shows moderate, complete membranous staining in >10% tumor cells on HER2 IHC. What is the correct interpretation?',
    options: ['Negative (Score 0)', 'Equivocal (Score 2+) — reflex ISH required', 'Positive (Score 3+)', 'Positive without need for ISH'],
    correctIndex: 1,
  ),
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'What is the size criterion for isolated tumor cells in breast carcinoma lymph node?',
    options: ['<0.2 mm', '<0.3 mm', '<0.1 mm', '<0.5 mm'],
    correctIndex: 0,
    explanation: 'Isolated tumor cells: <0.2 mm or less than 200 cells. Node designated pN0(i+).',
  ),
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'Positive internal mammary nodes indicate which N stage for breast carcinoma?',
    options: ['N2a', 'N2b', 'N2c', 'N3a'],
    correctIndex: 1,
    explanation: 'N2b: cancer cells spread to one or more internal mammary lymph nodes.',
  ),
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'Tall cell carcinoma with reverse polarity (TCCRP) of breast is associated with which mutation?',
    options: ['IDH2', 'BRCA1', 'p53', 'HER2neu'],
    correctIndex: 0,
    explanation: 'TCCRP is characterized by IDH2 mutations and reverse cellular polarity.',
  ),
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'What is the most common mutation in fibroadenoma?',
    options: ['BRCA1', 'p53', 'HER2', 'MED12 exon 2'],
    correctIndex: 3,
    explanation: 'Mutations in MED12, especially exon 2, are frequently observed in fibroadenomas.',
  ),
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'Which markers are used to separate usual ductal hyperplasia (UDH) versus atypical ductal hyperplasia (ADH)?',
    options: ['CK5/6 and ER', 'ER and PR', 'PR and Ki67', 'HER2neu and E-cadherin'],
    correctIndex: 0,
    explanation: 'UDH shows mosaic CK5/6 and focal ER; ADH shows uniform ER and lacks CK5/6.',
  ),
  QuizQuestion(
    topic: 'Breast Pathology',
    question: 'Adenoid cystic carcinoma of breast is typically:',
    options: ['ER+, PR+, HER2+', 'ER-, PR-, HER2-', 'ER+, PR-, HER2-', 'ER-, PR+, HER2+'],
    correctIndex: 1,
  ),
  // HEPATOBILIARY PATHOLOGY
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'Which IHC profile supports intrahepatic cholangiocarcinoma over hepatocellular carcinoma?',
    options: ['HepPar-1(+), Arginase-1(+), Glypican-3(+)', 'CK7(+), CK19(+), MOC31(+)', 'CDX2(+), CK20(+), SATB2(+)', 'Synaptophysin(+), Chromogranin(+)'],
    correctIndex: 1,
  ),
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'Which histologic feature is most characteristic of autoimmune hepatitis?',
    options: ['Ballooning degeneration', 'Interface hepatitis with plasma cells', 'Ground-glass hepatocytes', 'Perivenular fibrosis'],
    correctIndex: 1,
  ),
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'Map-like glutamine synthetase pattern on IHC supports which diagnosis?',
    options: ['HCC', 'β-catenin mutated hepatic adenoma', 'Focal nodular hyperplasia', 'Dysplastic nodule'],
    correctIndex: 2,
  ),
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'Mallory-Denk bodies in hepatocytes are formed due to:',
    options: ['Iron deposition', 'Copper deposits', 'Oxidative stress', 'α₁-antitrypsin deficiency'],
    correctIndex: 2,
    explanation: 'MDBs form due to misfolded proteins (cytokeratins 8 and 18) from oxidative stress.',
  ),
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'β-catenin mutated hepatic adenoma is associated with:',
    options: ['Hemorrhage', 'Risk of HCC', 'Spontaneous regression', 'Steatosis'],
    correctIndex: 1,
    explanation: 'β-catenin mutated hepatic adenoma has highest HCC risk among all adenoma types.',
  ),
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'The hallmark molecular alteration in fibrolamellar HCC is:',
    options: ['TERT promoter mutation', 'HBV integration', 'DNAJB1-PRKACA fusion', 'CTNNB1 mutation'],
    correctIndex: 2,
    explanation: 'DNAJB1-PRKACA fusion is pathognomonic for fibrolamellar HCC.',
  ),
  QuizQuestion(
    topic: 'Hepatobiliary Pathology',
    question: 'Which is NEGATIVE for Glypican-3?',
    options: ['HCC', 'Yolk sac tumor', 'Hepatoblastoma', 'Pancreatic adenocarcinoma'],
    correctIndex: 3,
    explanation: 'GPC3 is positive in HCC, yolk sac tumor, hepatoblastoma, but negative in pancreatic adenocarcinoma.',
  ),
  // PANCREATIC PATHOLOGY
  QuizQuestion(
    topic: 'Pancreatic Pathology',
    question: 'Which genetic alteration is most frequently seen in pancreatic ductal adenocarcinoma?',
    options: ['BRAF V600E mutation', 'KRAS codon 12 mutation', 'JAK2 V617F mutation', 'MYC amplification'],
    correctIndex: 1,
  ),
  QuizQuestion(
    topic: 'Pancreatic Pathology',
    question: 'Which pancreatic neoplasm shows nuclear β-catenin positivity and perivascular hyalinization?',
    options: ['Pancreatic ductal adenocarcinoma', 'Acinar cell carcinoma', 'Solid-pseudopapillary neoplasm', 'Pancreatic NET'],
    correctIndex: 2,
  ),
  QuizQuestion(
    topic: 'Pancreatic Pathology',
    question: 'Which hereditary syndrome is NOT associated with pancreatic NET?',
    options: ['VHL syndrome', 'MEN1 syndrome', 'NF1 syndrome', 'Lynch syndrome'],
    correctIndex: 3,
    explanation: 'Lynch syndrome causes pancreatic adenocarcinoma, not pancreatic NET.',
  ),
  // DERMATOPATHOLOGY
  QuizQuestion(
    topic: 'Dermatopathology',
    question: 'Which IHC marker is most consistently positive in desmoplastic melanoma?',
    options: ['HMB-45', 'Melan-A', 'S-100 protein', 'Cytokeratin AE1/AE3'],
    correctIndex: 2,
    explanation: 'Desmoplastic melanoma can be negative for HMB-45 and Melan-A; S-100 remains valuable.',
  ),
  QuizQuestion(
    topic: 'Dermatopathology',
    question: 'Epidermolysis bullosa acquisita (EBA) is caused by autoantibodies against:',
    options: ['Desmoglein 1', 'Type VII collagen', 'Laminin-332', 'BP180'],
    correctIndex: 1,
  ),
  QuizQuestion(
    topic: 'Dermatopathology',
    question: 'Which is the single most important histopathological prognostic factor in cutaneous melanoma?',
    options: ["Clark's level", 'Breslow thickness', 'Ulceration', 'Mitotic count'],
    correctIndex: 1,
    explanation: 'Breslow thickness (tumor depth in mm) is the single most important prognostic factor.',
  ),
  QuizQuestion(
    topic: 'Dermatopathology',
    question: 'A 44-year-old female with itchy rash on extensor surface. What is the likely DIF finding?',
    options: ['Linear IgG at dermo-epidermal junction', 'Linear IgA at dermo-epidermal junction', 'Granular IgA in dermal papillae', 'Intraepidermal intercellular IgG'],
    correctIndex: 2,
    explanation: 'Dermatitis Herpetiformis shows granular IgA deposits in papillary dermis.',
  ),
  // FORENSIC PATHOLOGY
  QuizQuestion(
    topic: 'Forensic Pathology',
    question: 'At autopsy, lungs are heavy with frothy fluid. Multiple needle marks in antecubital fossa. Toxicology reveals 6-MAM in femoral blood. Most likely cause of death?',
    options: ['Acute morphine toxicity', 'Acute heroin poisoning', 'Acute cocaine intoxication', 'Sudden cardiac death'],
    correctIndex: 1,
    explanation: '6-MAM (6-monoacetylmorphine) is a specific metabolite of heroin confirming heroin use.',
  ),
  QuizQuestion(
    topic: 'Forensic Pathology',
    question: 'In suspected post-mortem insulin overdose, which specimen is most useful for confirming hypoglycemia?',
    options: ['Cardiac blood', 'Femoral blood', 'Vitreous humour', 'Urine'],
    correctIndex: 2,
    explanation: 'Vitreous humour is the most reliable for post-mortem glucose measurement.',
  ),
  // GYNECOLOGICAL PATHOLOGY
  QuizQuestion(
    topic: 'Gynecological Pathology',
    question: 'PARP inhibitors are most effective in ovarian tumors with:',
    options: ['TP53 mutation only', 'Wild-type BRCA', 'Homologous recombination deficiency (HRD) including BRCA', 'Mismatch repair deficiency'],
    correctIndex: 2,
  ),
  QuizQuestion(
    topic: 'Gynecological Pathology',
    question: 'FOXL2 (402C→G) mutation is characteristic of which ovarian tumor?',
    options: ['Juvenile granulosa cell tumor', 'Adult granulosa cell tumor', 'Sertoli-Leydig cell tumor', 'Thecoma'],
    correctIndex: 1,
    explanation: 'FOXL2 C402G mutation is pathognomonic for adult granulosa cell tumor.',
  ),
  QuizQuestion(
    topic: 'Gynecological Pathology',
    question: 'High-grade serous ovarian carcinoma is MOST characteristically associated with:',
    options: ['KRAS mutation and low mitotic index', 'Wild-type p53 staining', 'Homologous recombination deficiency with genomic instability', 'ARID1A mutation and endometriosis'],
    correctIndex: 2,
    explanation: 'HGSOC: HRD and TP53 mutations in >95% of cases.',
  ),
  QuizQuestion(
    topic: 'Gynecological Pathology',
    question: 'What immunohistochemical profile is most consistent with mesonephric adenocarcinoma of the endometrium?',
    options: ['ER+, PR+, PAX8-', 'ER-, PR-, GATA3+, TTF-1+, CD10+', 'ER+, PR+, WT1+, p53 mutant', 'p16+, HPV+, GATA3+'],
    correctIndex: 1,
    explanation: 'Mesonephric adenocarcinoma: GATA3+, TTF-1+, CD10+, PAX2+.',
  ),
  // GENITOURINARY - PROSTATE
  QuizQuestion(
    topic: 'Genitourinary Pathology',
    question: 'Which hereditary mutation confers the highest risk of aggressive prostate carcinoma?',
    options: ['BRCA1', 'BRCA2', 'MLH1', 'PTEN'],
    correctIndex: 1,
    explanation: 'BRCA2 germline mutations confer the highest risk of aggressive prostate carcinoma.',
  ),
  QuizQuestion(
    topic: 'Genitourinary Pathology',
    question: 'Loss of PTEN staining in tumor glands with intact benign glands in prostate adenocarcinoma indicates:',
    options: ['Benign prostatic hyperplasia', 'Intraductal carcinoma', 'Poor prognosis and higher-grade tumor', 'ERG-negative tumor'],
    correctIndex: 2,
    explanation: 'Loss of PTEN is associated with poor prognosis and higher-grade prostate tumors.',
  ),
  // RENAL PATHOLOGY
  QuizQuestion(
    topic: 'Renal Pathology',
    question: 'Which IHC stain is most specific for lymphatic endothelium?',
    options: ['CD34', 'Factor VIII', 'D2-40 (podoplanin)', 'CD31'],
    correctIndex: 2,
  ),
  QuizQuestion(
    topic: 'Renal Pathology',
    question: 'A "basket-weave" appearance of the GBM on electron microscopy is indicative of:',
    options: ['Minimal change disease', 'Alport syndrome', 'Membranous nephropathy', 'IgA nephropathy'],
    correctIndex: 1,
    explanation: 'Alport syndrome is X-linked and caused by COL4A5 gene mutations.',
  ),
  QuizQuestion(
    topic: 'Renal Pathology',
    question: 'Which immunofluorescence pattern is typically absent in Dense Deposit Disease (DDD)?',
    options: ['C3', 'IgG', 'IgM', 'Both IgG and IgM'],
    correctIndex: 3,
    explanation: 'Both IgG and IgM are absent in DDD; only C3 is deposited.',
  ),
  QuizQuestion(
    topic: 'Renal Pathology',
    question: 'The hallmark of Renal Medullary Carcinoma is the loss of:',
    options: ['INI-1 (SMARCB1)', 'PAX8', 'TFE3', 'CD117'],
    correctIndex: 0,
    explanation: 'Renal medullary carcinoma: loss of INI-1 (SMARCB1) expression.',
  ),
  // HEMATOPATHOLOGY
  QuizQuestion(
    topic: 'Hematopathology',
    question: 'Which laboratory finding is MOST critical to monitor in tumor lysis syndrome (TLS)?',
    options: ['Hypokalemia', 'Hypophosphatemia', 'Hyperkalemia', 'Hypocalcemia'],
    correctIndex: 2,
    explanation: 'Hyperkalemia is the most critical finding in TLS — can cause cardiac arrest.',
  ),
  QuizQuestion(
    topic: 'Hematopathology',
    question: 'NPM1 mutations in AML serve as:',
    options: ['Rarely used due to instability', 'Stable biomarkers for tracking residual disease', 'Indicators of chemotherapy resistance', 'Only relevant at diagnosis'],
    correctIndex: 1,
    explanation: 'NPM1 mutations are stable during disease evolution and tracked for MRD via RT-qPCR.',
  ),
  QuizQuestion(
    topic: 'Hematopathology',
    question: 'A 50-year-old with M spike 2.4 g/dL, no CRAB features, 15% bone marrow plasma cells. Diagnosis?',
    options: ['Multiple myeloma', 'Smoldering multiple myeloma', 'MGUS', 'Plasmacytoma'],
    correctIndex: 1,
    explanation: 'SMM: M protein ≥3 g/dL and/or 10-60% clonal plasma cells, no CRAB criteria.',
  ),
  QuizQuestion(
    topic: 'Hematopathology',
    question: 'A lymph node shows cells CD20+, BCL6+, EMA+, strong PAX5+, CD30-, CD15-. Most likely diagnosis?',
    options: ['Classic Hodgkin lymphoma', 'NLPHL', 'THRLBCL', 'PMBCL'],
    correctIndex: 1,
    explanation: 'NLPHL: LP cells are CD20+, BCL6+, EMA+, strong PAX5+, CD30-, CD15-.',
  ),
  QuizQuestion(
    topic: 'Hematopathology',
    question: 'In WHO 5th Edition classification, AITL is categorized under:',
    options: ['Peripheral T-cell lymphoma NOS', 'Mature T-cell leukemia/lymphoma', 'Nodal T-follicular helper cell lymphoma', 'EBV-associated T-cell lymphoma'],
    correctIndex: 2,
    explanation: 'WHO 5th (2022): AITL classified under Nodal TFH cell lymphoma.',
  ),
  QuizQuestion(
    topic: 'Hematopathology',
    question: 'Which is NOT associated with HHV-8 virus?',
    options: ['Primary effusion lymphoma', 'Multicentric Castleman disease', 'Kaposi sarcoma', 'Angioimmunoblastic T-cell lymphoma'],
    correctIndex: 3,
    explanation: 'AITL is associated with EBV, not HHV-8.',
  ),
  // COLORECTAL PATHOLOGY
  QuizQuestion(
    topic: 'Gastrointestinal Pathology',
    question: 'What is the most common mutation in KIT receptor for GIST?',
    options: ['Exon 9', 'Exon 11', 'Exon 13', 'Exon 17'],
    correctIndex: 1,
    explanation: 'Exon 11 (codons 557-558) is the most common site of KIT mutations in GIST.',
  ),
  QuizQuestion(
    topic: 'Gastrointestinal Pathology',
    question: 'MSI in HNPCC is due to defect in which gene?',
    options: ['APC', 'MLH1', 'P53', 'KRAS'],
    correctIndex: 1,
    explanation: 'MLH1 is one of the key genes responsible for microsatellite stability.',
  ),
  QuizQuestion(
    topic: 'Gastrointestinal Pathology',
    question: 'FAP carries approximately what risk of developing colorectal carcinoma by age 40 if untreated?',
    options: ['20-30%', '40-50%', '60-70%', '>90%'],
    correctIndex: 3,
    explanation: 'FAP: >90% risk of CRC by age 40 without prophylactic colectomy.',
  ),
  QuizQuestion(
    topic: 'Gastrointestinal Pathology',
    question: 'What pH is used for Alcian blue stain for Barrett\'s esophagus?',
    options: ['2.5', '4', '8', '9'],
    correctIndex: 0,
    explanation: 'Alcian blue at pH 2.5 stains acid mucins in Barrett\'s esophagus.',
  ),
  // PULMONARY PATHOLOGY
  QuizQuestion(
    topic: 'Pulmonary Pathology',
    question: 'A biopsy shows loss of BRG1 expression in a mediastinal tumor. Most likely diagnosis?',
    options: ['Large Cell Neuroendocrine Carcinoma', 'SMARCA4-Deficient Undifferentiated Thoracic Tumor', 'Squamous Cell Carcinoma', 'Adenocarcinoma'],
    correctIndex: 1,
    explanation: 'Loss of BRG1 is diagnostic of SMARCA4-DUT.',
  ),
  QuizQuestion(
    topic: 'Pulmonary Pathology',
    question: 'The presence of fibroblastic foci in patchy, subpleural distribution is characteristic of:',
    options: ['Organizing pneumonia', 'NSIP', 'UIP', 'Hypersensitivity pneumonitis'],
    correctIndex: 2,
    explanation: 'Fibroblastic foci are part of temporal heterogeneity in UIP/IPF.',
  ),
  QuizQuestion(
    topic: 'Pulmonary Pathology',
    question: 'Most common cause of pulmonary alveolar proteinosis in adults is:',
    options: ['Silica exposure', 'Hematologic malignancy', 'Anti-GM-CSF antibodies', 'Surfactant protein gene mutation'],
    correctIndex: 2,
    explanation: 'Autoimmune PAP caused by anti-GM-CSF antibodies is the most common form (~90%).',
  ),
  QuizQuestion(
    topic: 'Pulmonary Pathology',
    question: 'Most likely resistance mechanism to first-generation EGFR TKIs in lung adenocarcinoma?',
    options: ['ALK fusion', 'Small cell transformation', 'EGFR T790M mutation', 'KRAS mutation'],
    correctIndex: 2,
    explanation: 'EGFR T790M mutation is the most common resistance mechanism (~50-60%).',
  ),
  QuizQuestion(
    topic: 'Pulmonary Pathology',
    question: 'Which histologic feature best predicts poor prognosis in lung adenocarcinoma regardless of stage?',
    options: ['Lepidic growth pattern', 'Presence of mucin', 'Micropapillary pattern', 'TTF-1 positivity'],
    correctIndex: 2,
    explanation: 'Micropapillary pattern: strongly linked to lymphovascular invasion and recurrence.',
  ),
  // MOLECULAR PATHOLOGY
  QuizQuestion(
    topic: 'Molecular Pathology',
    question: 'Which metabolite accumulates as a result of IDH1 mutation?',
    options: ['Fumarate', 'Succinate', '2-hydroxyglutarate', 'α-ketoglutarate'],
    correctIndex: 2,
    explanation: '2-hydroxyglutarate (2-HG) is an oncometabolite that accumulates with IDH mutations.',
  ),
  QuizQuestion(
    topic: 'Molecular Pathology',
    question: 'In oligodendrogliomas, 1p/19q codeletion is best defined as:',
    options: ['Partial loss of 1p and 19q', 'Whole-arm combined loss of 1p and 19q', 'Loss of 1p only', 'Seen in glioblastoma with EGFR amplification'],
    correctIndex: 1,
    explanation: 'True oligodendroglioma requires whole-arm 1p + 19q loss from t(1;19)(q10;p10).',
  ),
  // NEUROPATHOLOGY
  QuizQuestion(
    topic: 'Neuropathology',
    question: 'H3.3 G34W mutation is specific for which bone tumor?',
    options: ['Giant cell tumor of bone', 'Chondroblastoma', 'Brown tumor of hyperparathyroidism', 'Telangiectatic osteosarcoma'],
    correctIndex: 0,
    explanation: 'H3.3 G34W is specific mutation for giant cell tumor of bone.',
  ),
  // CLINICAL GOVERNANCE
  QuizQuestion(
    topic: 'Clinical Governance',
    question: 'Non-participation in EQA scheme leading to incorrect HER2 scoring most directly breaches which pillar?',
    options: ['Risk management', 'Clinical effectiveness', 'Patient and public involvement', 'Audit and clinical effectiveness'],
    correctIndex: 3,
    explanation: 'Non-participation in EQA schemes directly breaches audit and clinical effectiveness.',
  ),
  QuizQuestion(
    topic: 'Clinical Governance',
    question: 'Following breast FNAC was misreported as C3. On realizing the error, pathologist should:',
    options: ['Wait for repeat FNAC', 'Amend to C5, inform surgeon, and file incident report', 'Discuss only at audit', 'Ignore since repeat is planned'],
    correctIndex: 1,
  ),
];
